name: Build Typst document
on: [push]
jobs:
  build_typst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disable automatic token authentication
      - name: Compile Typst Files
        uses: lvignoli/typst-action@main
        with:
          source_file: typst_report/main.typ
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add typst_report/main.pdf
          git commit -m "Add compiled Typst document"
          git push
