name: Build Typst document
on: [push]
jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compile Typst Files
        uses: lvignoli/typst-action@main
        with:
          source_file: typst_report/main.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: typst_report/main.pdf
